# SPDX-License-Identifier: Apache-2.0
"""Package the shared SQLite schema; --check detects drift without rewriting."""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
sql = (root / "schemas/persistence/sqlite-0.1.sql").read_text(encoding="utf-8")
outputs = {
    "implementations/typescript/packages/api-server/src/storage-schema.ts": "// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate-persistence-schema.py; embedded schema is CC0.\nexport const STORAGE_SCHEMA = " + json.dumps(sql) + ";\n",
    "implementations/python/packages/api-server/src/psp_cdl_api_server/storage_schema.py": "# SPDX-License-Identifier: Apache-2.0\n# Generated by scripts/generate-persistence-schema.py; embedded schema is CC0.\nSTORAGE_SCHEMA = " + repr(sql) + "\n",
}
for name, content in outputs.items():
    path = root / name
    if "--check" in sys.argv:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Schema drift: " + name)
    else:
        path.write_text(content, encoding="utf-8")
print("Persistence schema copies agree.")
