# SPDX-License-Identifier: Apache-2.0
"""Generate draft CC0 wire schemas and packaged tool definitions from one contract."""
import json
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
def obj(properties,required=None):
    return {"type":"object","additionalProperties":False,"properties":properties,"required":list(properties) if required is None else required}
identifier={"type":"string","minLength":1,"maxLength":128,"pattern":"^[A-Za-z0-9][A-Za-z0-9._:-]*$","not":{"pattern":"[^A-Za-z0-9._:-]"}}
verify=obj({"operation_id":identifier,"sections":{"type":"array","minItems":1,"maxItems":32,"items":obj({"id":identifier,"content":{"type":"string"}})}})
evaluate=obj({"operation_id":identifier})
common={"profile":{"const":"PSP-SERVICE-0.1"},"operation_id":identifier,"policy_version":identifier}
valid=obj({"id":identifier,"valid":{"const":True},"signature_algorithm":{"enum":["ed25519","hmac-sha256"]},"trust_level":{"type":"integer","minimum":0,"maximum":5},"priority":{"type":"number","minimum":0,"maximum":100},"expires":{"type":"integer","minimum":0}})
invalid=obj({"id":identifier,"valid":{"const":False},"error":{"type":"string"}})
verify_out=obj({**common,"results":{"type":"array","items":{"oneOf":[valid,invalid]}},"summary":obj({k:{"type":"integer","minimum":0} for k in ("total","valid","invalid")})})
evaluate_out=obj({**common,"decision":{"enum":["allow","deny","unsupported"]},"reasonCodes":{"type":"array","items":{"type":"string"},"uniqueItems":True}})
tools=[{"name":name,"description":description,"inputSchema":request,"outputSchema":output,"annotations":{"readOnlyHint":True,"destructiveHint":False,"idempotentHint":True,"openWorldHint":False}} for name,description,request,output in [
    ("realflow.security.verify","Verify a batch of signed leaf sections against host-owned operation authority.",verify,verify_out),
    ("realflow.policy.evaluate","Evaluate a host-owned operation policy snapshot; this result is not a dispatch permit.",evaluate,evaluate_out)]]
schemas={"VerifyRequest":verify,"EvaluateRequest":evaluate,"VerifyResponse":verify_out,"EvaluateResponse":evaluate_out,"Error":obj({"error":obj({"code":{"type":"string"}})})}
paths={}
for path,method,request,output in [("/v1/security/verify","verify","VerifyRequest","VerifyResponse"),("/v1/policy/evaluate","evaluate","EvaluateRequest","EvaluateResponse")]:
    responses={"200":{"description":"Scoped result; a policy denial or invalid signature can be reported within this successful evaluation.","content":{"application/json":{"schema":{"$ref":"#/components/schemas/"+output}}}}}
    for code in (400,401,403,404,405,409,413,415,500):
        responses[str(code)]={"description":"Fail-closed service error","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Error"}}}}
    paths[path]={"post":{"operationId":method,"security":[{"bearerAuth":[]}],"requestBody":{"required":True,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/"+request}}}},"responses":responses}}
openapi={"openapi":"3.1.0","info":{"title":"PSP reference security service (draft)","version":"0.1.0","description":"PSP-SERVICE-0.1; project-owned draft, not the missing RFC-PSP-API. Read-only operations; no workflow authorization ticket."},"paths":paths,"components":{"securitySchemes":{"bearerAuth":{"type":"http","scheme":"bearer","description":"Opaque host-validated token. The host owns tenant, subject, scopes, expiry and revocation."}},"schemas":schemas}}
outputs={
    'schemas/api/security-0.1.openapi.json':json.dumps(openapi,indent=2)+'\n',
    'schemas/mcp/security-tools-0.1.json':json.dumps({'profile':'PSP-SERVICE-0.1','protocolVersion':'2025-11-25','tools':tools},indent=2)+'\n',
    'implementations/typescript/packages/mcp-server/src/tools.ts':'// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate-service-contracts.py from public-domain wire contracts.\nexport const toolDefinitions = '+json.dumps(tools,indent=2)+';\n',
    'implementations/python/packages/mcp-server/src/psp_cdl_mcp_server/tools.py':'# SPDX-License-Identifier: Apache-2.0\n# Generated from public-domain wire contracts.\nimport json\nTOOL_DEFINITIONS = json.loads('+repr(json.dumps(tools,separators=(',',':')))+')\n',
}
for name,text in outputs.items():
    path=ROOT/name
    if sys.argv[1:]==['--check']:
        assert path.read_bytes()==text.encode('utf-8'),name+' differs'
    elif not sys.argv[1:]:
        path.write_text(text,encoding='utf-8',newline='\n')
    else:
        raise SystemExit('Use --check or no arguments.')
print('Four service contract artifacts agree.')
